name: Deploy Backend
on:
    push:
        branches:
            - main

jobs:
    redeploy:
        runs-on: ubuntu-latest
        name: redeploy-everything
        steps:
            - run: |
                ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@139.59.58.88 << 'EOF'
                set -x
                cd ~/devops-three || (git clone https://github.com/ganeshnaidudsa/devops-three.git && cd devops-three)
                git pull origin main  # Pull latest changes
                npm install
                npm run build  # Ensure the build is done
                pm2 restart index || pm2 start dist/index.js --name index
                pm2 save
                EOF
