name: Deploy Backend
on:
    push:
        branches:
            - main

jobs:
    redeploy:
        runs-on: ubuntu-latest
        name: redeploy-everything
        steps:
            - run: |
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
                chmod 700 ~/ssh_key
                ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@139.59.58.88 -t "
                cd ~/devops-three && \
                git pull origin main && \
                npm install && \
                npm run build && \
                pm2 stop all && \
                pm2 delete all && \
                pm2 start dist/index.js --name my-backend"
