name: Deploy Backend
on:
    push:
        branches:
            - main

jobs:
    redeploy:
        runs-on: ubuntu-latest
        name: redeploy-everything
        steps:
            - run: |
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
                chmod 700 ~/ssh_key
                ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@139.59.58.88 -t "
                cd ~/devops-three || (git clone https://github.com/ganeshnaidudsa/devops-three.git && cd devops-three)
                git pull origin && \
                npm install && \
                npm run build && \
                pm2 delete index && pm2 start dist/index.js --name index"
